// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("5.0.0.1")]
[assembly: AssemblyFileVersionAttribute("5.0.0.1")]
[assembly: AssemblyInformationalVersionAttribute("5.0.0.1 4c92af")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "5.0.0.1";
        internal const System.String AssemblyFileVersion = "5.0.0.1";
        internal const System.String AssemblyInformationalVersion = "5.0.0.1 4c92af";
    }
}
