using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;

namespace Simple.OData.Client.Tests
{
    public class InsertDynamicTests : TestBase
    {
        [Fact]
        public void Insert()
        {
            var x = ODataDynamic.Expression;
            var product = _client
                .For(x.Products)
                .Set(x.ProductName = "Test1", x.UnitPrice = 18m)
                .InsertEntry();

            Assert.Equal("Test1", product.ProductName);
        }

        [Fact]
        public void InsertAutogeneratedID()
        {
            var x = ODataDynamic.Expression;
            var product = _client
                .For(x.Products)
                .Set(x.ProductName = "Test1", x.UnitPrice = 18m)
                .InsertEntry();

            Assert.True((int)product.ProductID > 0);
            Assert.Equal("Test1", product.ProductName);
        }

        [Fact]
        public void InsertProductWithCategoryByID()
        {
            var x = ODataDynamic.Expression;
            var category = _client
                .For(x.Categories)
                .Set(x.CategoryName = "Test3")
                .InsertEntry();
            var product = _client
                .For(x.Products)
                .Set(x.ProductName = "Test4", x.UnitPrice = 18m, x.CategoryID = category.CategoryID)
                .InsertEntry();

            Assert.Equal("Test4", product.ProductName);
            Assert.Equal(category.CategoryID, product.CategoryID);
            category = _client
                .For(x.Categories)
                .Expand(x.Products)
                .Filter(x.CategoryName == "Test3")
                .FindEntry();
            Assert.True((category.Products as IEnumerable<dynamic>).Count() == 1);
        }

        [Fact]
        public void InsertProductWithCategoryByAssociation()
        {
            var x = ODataDynamic.Expression;
            var category = _client
                .For(x.Categories)
                .Set(x.CategoryName = "Test5")
                .InsertEntry();
            var product = _client
                .For(x.Products)
                .Set(x.ProductName = "Test6", x.UnitPrice = 18m, x.Category = category)
                .InsertEntry();

            Assert.Equal("Test6", product.ProductName);
            Assert.Equal(category.CategoryID, product.CategoryID);
            category = _client
                .For(x.Categories)
                .Expand(x.Products)
                .Filter(x.CategoryName == "Test5")
                .FindEntry();
            Assert.True((category.Products as IEnumerable<dynamic>).Count() == 1);
        }
    }
}
