// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("5.10.0.0")]
[assembly: AssemblyFileVersionAttribute("5.10.0.0")]
[assembly: AssemblyInformationalVersionAttribute("5.10.0.0 4c92af")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "5.10.0.0";
        internal const System.String AssemblyFileVersion = "5.10.0.0";
        internal const System.String AssemblyInformationalVersion = "5.10.0.0 4c92af";
    }
}
